services:
  postgres:
    image: postgres:latest
    container_name: jdbc_aston
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./data/mount:/var/lib/postgresql/data